"""
@author: Marcos Chindelar
"""

ENERGY_CAPACITY = 0
LOAD_CAPACITY = 0.00
ENERGY_CONSUPTION = 0.00
DISTANCE_MATRIX = []
LOCATIONS = []
NUM_LOCATIONS = 0
CUSTOMERS = []
NUM_CUSTOMERS = 0
STATIONS = []
NUM_STATIONS = 0
ARCHIVE_NAME = ""
CI = 4
CE = 1